title: Android
email: kartiku@groww.in
description: >-
  Documentation for Android Platform libraries
baseurl: "/android" 
url: "https://kartikssj.github.io"
theme: just-the-docs
plugins:
  - jekyll-feed

